source 'https://rubygems.org'

gem 'bourbon'
gem 'neat'
gem 'coffee-rails', '~> 4.0.0'
gem 'high_voltage', '~> 2.2.1'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'monban'
gem 'monban-generators'
gem 'pg'
gem 'rails', '4.1.6'
gem 'rails_12factor'
gem 'sass-rails', '~> 4.0.3'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'uglifier', '>= 1.3.0'
